### ISSUE TITLE
This is great, however vanilla app hangs on iOS load?

### ISSUE THREAD

**Issue by michaeldimoudis** [adamped/xarch-starter#1]
Hi I just downloaded this and built it. When I run it in the iOS simulator it just hangs on load. Is this an issue or do I have to configure anything to get the base vanilla app going?

**Comment by adamped** [comment]
It shouldn't. Please give me a few hours and I will check into this for you. What is the exact stage that it hangs at, does it hang on a particular page in the app, the splashscreen or before the simulator even loads?

**Comment by michaeldimoudis** [comment]
Thanks. It's hanging on LoadApplication() in AppDelegate. Does't seem to hit any breakpoint in new App().

**Comment by adamped** [comment]
Are you using a Mac Build Host or building on a Mac? I normally find that iOS deploys can hang just because of a bad connection with the Mac Build Host. Also do you have Xamarin 4 yet?

Apologies I am not going to be able to test it for another 7 ish hours as teh VPN to my Mac Build Host is down right now and I need to get home to reactivate it again. However looking at the code the iOS project is really bare. It shouldn't be anything within the project, so I am suspecting an environmental issue. If you create a blank iOS project on your end and run that with XF 2.0 does that run successfully?

**Comment by adamped** [comment]
The issue has now been resolved. Apologies, it was my error on returning a non completing empty task on a non-overridden OnNavigated event.
