### ISSUE TITLE
How would I implement a TabbedPage?

### ISSUE THREAD

**Issue by michaeldimoudis** [adamped/xarch-starter#3]
Hi I tried putting TabbedPage in place of MasterDetailPage in MainStack.cs, but I need NavigationPages in each tab, so I could only get the first tab navigating properly. Any tips how I could do this?

**Comment by adamped** [comment]
That is interesting. The only thing I can think of, off the top of my head
at this late hour is the stack storing a list of NavigationPage's and the
push/pop being done on the navigation page based on the current tab which
would have to be changed on an event that happens when you view a new tab.
Not sure, but I think there is an event for when a tab page is changed,
otherwise OnAppearing might have to be used.

So the Stack would track what page, hence navigation page was in view.

Certainly sounds like it could get messy.

More ideally it would be better if the navigate function knew which page it
was in, hence which navigation page. That way would certainly be less prone
to errors but would have to think that one through some more.

On Thu, Mar 10, 2016 at 11:02 PM, Michael Dimoudis <notifications@github.com

**Comment by adamped** [comment]
Well I'm going to close this, as Exrin.net would be the best way to support a TabbedPage. :)
